# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Pytest

on:
  workflow_run:
    workflows: ["Pylint"]
    branches: [ "*" ]
    types: 
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install
        - name: Testing the code using Pytest
          run: |
            poetry run coverage run -m pytest .
            poetry run coverage xml --fail-under=90
        - name: Get Cover 
          uses: orgoro/coverage@v3.2
          with:
              coverageFile: ./coverage.xml
              token: ${{ secrets.GITHUB_TOKEN }}
